name: Lint Code

# Define inputs for the action, such as the project folder to lint
inputs:
  src-project-folder:
    description: "Directory where the project is located"
    required: true
    default: "src"

runs:
  using: composite
  steps:
    # Step 1: Check format with Black (code formatter)
    - name: Check format with Black
      run: |
        echo "Running Black formatter check..."  
        poetry run black --check ${{ inputs.src-project-folder }}/
      shell: bash